export enum RideStatuses {
    SCHEDULED = 'SCHEDULED',
    DRIVER_EN_ROUTE = 'DRIVER_EN_ROUTE',
    DRIVER_ARRIVED = 'DRIVER_ARRIVED',
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    NO_SHOW = 'NO_SHOW',
}
